[package]
name = "evil_alligator"
version = "0.2.0"
authors = ["Ricardo Ribeiro <rsribeiro916@gmail.com>"]
edition = "2018"

[dependencies]
specs = "0.14.3"
specs-derive = "0.4.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.rand]
version = "0.6.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
stdweb = "0.4.13"

[target.'cfg(target_arch = "wasm32")'.dependencies.rand]
version = "0.6.5"
features = ["stdweb"]

[dependencies.quicksilver]
version = "0.3.6"
path = "../quicksilver"
default-features = false
features = ["fonts", "sounds"]

[profile.release]
lto = true
#sem nada web=1046KB/win64=2345KB
opt-level = 's' #web=798KB/1684KB
#opt-level = 'z' #web=872KB/1639KB